### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by NoMoreNap** [skypro-web-developer/webdev-react-hw-template#1]
Напишите в документацию, что нужно прокидывать заголовок авторизации, чтобы можно было добавить трек в избранное
`"Authorization": "Bearer <token>"`

**Comment by GlebkaF** [comment]
Привет, обязательно напишу, но позже, пока можешь посмотреть примеры запросов с авторизацией в сваггер доке

**Comment by GlebkaF** [comment]
Готово
